### ISSUE TITLE
Create a raised circular button

### ISSUE THREAD

**Issue by supratik94** [angeldev/iOSDev#1]
How do to I make the button circular?
Something like this:
![screen shot 2016-03-15 at 6 49 59 pm](https://cloud.githubusercontent.com/assets/7619684/13778974/bf48a3d0-eade-11e5-80b1-cfd9c435262d.png)

**Comment by angeldev** [comment]
I have just added the code for this case. You just have to consider that the height of the image is bigger than the tabBar, so when you set the center of the image you have to add the half of the difference between the heights.

```
var center: CGPoint = self.tabBar.center
center.y = center.y - heightDifference / 2.0
cameraButton.center = center
```
